/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import sk.upjs.ics.paz1c.obchodnaSiet.dao.DaoFactory;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Nastavenia;

/**
 *
 * @author Student
 */
public class HlavneOknoForm extends javax.swing.JFrame {

    /**
     * Creates new form HlavneOknoForm
     */
    public HlavneOknoForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Nastavenia nastavenia= DaoFactory.INSTANCE.getNastaveniaDao().nacitajNastavenia(1);
        nazovObchodnejSieteLabel.setText(nastavenia.getNazovObchodnejSiete());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nazovObchodnejSieteLabel = new javax.swing.JLabel();
        prevadzkyButton = new javax.swing.JButton();
        zamestnanciButton = new javax.swing.JButton();
        produktButton = new javax.swing.JButton();
        nastaveniaButton = new javax.swing.JButton();
        oProgrameButton = new javax.swing.JButton();
        koniecButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Obchodná sieť");

        nazovObchodnejSieteLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nazovObchodnejSieteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nazovObchodnejSieteLabel.setText("Názov obchodnej siete");

        prevadzkyButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        prevadzkyButton.setText("Prevádzky");
        prevadzkyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevadzkyButtonActionPerformed(evt);
            }
        });

        zamestnanciButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        zamestnanciButton.setText("Zamestnanci");
        zamestnanciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamestnanciButtonActionPerformed(evt);
            }
        });

        produktButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        produktButton.setText("Produkty");
        produktButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produktButtonActionPerformed(evt);
            }
        });

        nastaveniaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nastaveniaButton.setText("Nastavenia");
        nastaveniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastaveniaButtonActionPerformed(evt);
            }
        });

        oProgrameButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        oProgrameButton.setText("O programe");
        oProgrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oProgrameButtonActionPerformed(evt);
            }
        });

        koniecButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        koniecButton.setText("Koniec");
        koniecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koniecButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nazovObchodnejSieteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(prevadzkyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zamestnanciButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(produktButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nastaveniaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oProgrameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(koniecButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nazovObchodnejSieteLabel)
                .addGap(18, 18, 18)
                .addComponent(prevadzkyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zamestnanciButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(produktButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nastaveniaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oProgrameButton)
                    .addComponent(koniecButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oProgrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oProgrameButtonActionPerformed
        new OProgrameForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_oProgrameButtonActionPerformed

    private void koniecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koniecButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_koniecButtonActionPerformed

    private void nastaveniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastaveniaButtonActionPerformed
        new NastaveniaForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nastaveniaButtonActionPerformed

    private void produktButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produktButtonActionPerformed
        new ProdutkyForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_produktButtonActionPerformed

    private void zamestnanciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamestnanciButtonActionPerformed
        new ZamestnanciForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_zamestnanciButtonActionPerformed

    private void prevadzkyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevadzkyButtonActionPerformed
        new PrevadzkyForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prevadzkyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavneOknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavneOknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavneOknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavneOknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavneOknoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton koniecButton;
    private javax.swing.JButton nastaveniaButton;
    private javax.swing.JLabel nazovObchodnejSieteLabel;
    private javax.swing.JButton oProgrameButton;
    private javax.swing.JButton prevadzkyButton;
    private javax.swing.JButton produktButton;
    private javax.swing.JButton zamestnanciButton;
    // End of variables declaration//GEN-END:variables
}
