package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import sk.upjs.ics.paz1c.obchodnaSiet.dao.DaoFactory;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Nastavenia;

public class NastaveniaForm extends javax.swing.JFrame {

    public NastaveniaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nastaveniaLabel = new javax.swing.JLabel();
        nazovObchodnejSieteLabel = new javax.swing.JLabel();
        nazovObchodnejSieteTextField = new javax.swing.JTextField();
        menaLabel = new javax.swing.JLabel();
        menaTextField = new javax.swing.JTextField();
        spatButton = new javax.swing.JButton();
        ulozitZmenyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        nastaveniaLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nastaveniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nastaveniaLabel.setText("Nastavenia");

        nazovObchodnejSieteLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nazovObchodnejSieteLabel.setText("Názov obchodnej siete:");

        nazovObchodnejSieteTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nazovObchodnejSieteTextField.setToolTipText("Názov obchodnej siete");
        nazovObchodnejSieteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazovObchodnejSieteTextFieldActionPerformed(evt);
            }
        });

        menaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menaLabel.setText("Mena:");

        menaTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menaTextField.setToolTipText("Mena obchodnej siete (max 5 znakov)");
        menaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menaTextFieldActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        ulozitZmenyButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ulozitZmenyButton.setText("Uložiť zmeny");
        ulozitZmenyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulozitZmenyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nastaveniaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nazovObchodnejSieteTextField)
                    .addComponent(menaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nazovObchodnejSieteLabel)
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addComponent(menaTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spatButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ulozitZmenyButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nastaveniaLabel)
                .addGap(18, 18, 18)
                .addComponent(nazovObchodnejSieteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazovObchodnejSieteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ulozitZmenyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(spatButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new HlavneOknoForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    private void nazovObchodnejSieteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazovObchodnejSieteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazovObchodnejSieteTextFieldActionPerformed

    private void menaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menaTextFieldActionPerformed

    private void ulozitZmenyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulozitZmenyButtonActionPerformed
        // TODO add your handling code here:
        Nastavenia nastavenia = new Nastavenia();
        nastavenia.setNazovObchodnejSiete(nazovObchodnejSieteTextField.getText());
        nastavenia.setMena(menaTextField.getText());

        DaoFactory.INSTANCE.getNastaveniaDao().pridajUpravNastavenia(nastavenia);

        dispose();
    }//GEN-LAST:event_ulozitZmenyButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NastaveniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NastaveniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NastaveniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NastaveniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NastaveniaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel menaLabel;
    private javax.swing.JTextField menaTextField;
    private javax.swing.JLabel nastaveniaLabel;
    private javax.swing.JLabel nazovObchodnejSieteLabel;
    private javax.swing.JTextField nazovObchodnejSieteTextField;
    private javax.swing.JButton spatButton;
    private javax.swing.JButton ulozitZmenyButton;
    // End of variables declaration//GEN-END:variables
}
