/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.obchodnaSiet.forms;

/**
 *
 * @author Student
 */
public class ZamestnanciForm extends javax.swing.JFrame {

    /**
     * Creates new form ZamestnanciForm
     */
    public ZamestnanciForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moznostiZobrazeniaButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        zamestnanciList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        pridatZamestnancaNaPrevadzkuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pridatZamestnancaButton = new javax.swing.JButton();
        prevadzkyComboBox = new javax.swing.JComboBox<>();
        spatButton = new javax.swing.JButton();
        odobratZamestnancaButton = new javax.swing.JButton();
        vsetciZamestnanciRadioButton = new javax.swing.JRadioButton();
        zamestnanciNaPrevadzkeRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        zamestnanciList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        zamestnanciList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(zamestnanciList);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zamestnanci");

        pridatZamestnancaNaPrevadzkuButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatZamestnancaNaPrevadzkuButton.setText("Pridať zamestnanca na prevádzku");
        pridatZamestnancaNaPrevadzkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatZamestnancaNaPrevadzkuButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Prevádzka:");

        pridatZamestnancaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatZamestnancaButton.setText("Pridať zamestnanca");
        pridatZamestnancaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatZamestnancaButtonActionPerformed(evt);
            }
        });

        prevadzkyComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        prevadzkyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        odobratZamestnancaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        odobratZamestnancaButton.setText("Odobrať zamestnanca");
        odobratZamestnancaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratZamestnancaButtonActionPerformed(evt);
            }
        });

        moznostiZobrazeniaButtonGroup.add(vsetciZamestnanciRadioButton);
        vsetciZamestnanciRadioButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        vsetciZamestnanciRadioButton.setSelected(true);
        vsetciZamestnanciRadioButton.setText("Všetci zamestnanci");
        vsetciZamestnanciRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsetciZamestnanciRadioButtonActionPerformed(evt);
            }
        });

        moznostiZobrazeniaButtonGroup.add(zamestnanciNaPrevadzkeRadioButton);
        zamestnanciNaPrevadzkeRadioButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        zamestnanciNaPrevadzkeRadioButton.setText("Podľa prevádzky");
        zamestnanciNaPrevadzkeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamestnanciNaPrevadzkeRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vsetciZamestnanciRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zamestnanciNaPrevadzkeRadioButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prevadzkyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridatZamestnancaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(odobratZamestnancaButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridatZamestnancaNaPrevadzkuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spatButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prevadzkyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vsetciZamestnanciRadioButton)
                    .addComponent(zamestnanciNaPrevadzkeRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatZamestnancaButton)
                    .addComponent(odobratZamestnancaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatZamestnancaNaPrevadzkuButton)
                    .addComponent(spatButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatZamestnancaNaPrevadzkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatZamestnancaNaPrevadzkuButtonActionPerformed
        new PridatZamestnancaNaPrevadzkuForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pridatZamestnancaNaPrevadzkuButtonActionPerformed

    private void pridatZamestnancaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatZamestnancaButtonActionPerformed
        new PridatZamestnancaForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pridatZamestnancaButtonActionPerformed

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new HlavneOknoForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    private void odobratZamestnancaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratZamestnancaButtonActionPerformed
        new OdobratZamestnancaDialogForm(this, true).setVisible(true);
    }//GEN-LAST:event_odobratZamestnancaButtonActionPerformed

    private void vsetciZamestnanciRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsetciZamestnanciRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vsetciZamestnanciRadioButtonActionPerformed

    private void zamestnanciNaPrevadzkeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamestnanciNaPrevadzkeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zamestnanciNaPrevadzkeRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZamestnanciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZamestnanciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZamestnanciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZamestnanciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZamestnanciForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup moznostiZobrazeniaButtonGroup;
    private javax.swing.JButton odobratZamestnancaButton;
    private javax.swing.JComboBox<String> prevadzkyComboBox;
    private javax.swing.JButton pridatZamestnancaButton;
    private javax.swing.JButton pridatZamestnancaNaPrevadzkuButton;
    private javax.swing.JButton spatButton;
    private javax.swing.JRadioButton vsetciZamestnanciRadioButton;
    private javax.swing.JList<String> zamestnanciList;
    private javax.swing.JRadioButton zamestnanciNaPrevadzkeRadioButton;
    // End of variables declaration//GEN-END:variables
}
